name: CI

on: [ push, pull_request, workflow_dispatch ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.0
      - name: Install dependencies
        run: poetry install
      - name: Black
        run: poetry run black src --check
      - name: Flake8
        run: poetry run flake8
      - name: Mypy
        run: poetry run mypy src --check-untyped-defs
      - name: Copy test envvars
        run: cp .env.test .env
      - name: Start docker containers
        run: docker-compose up --detach
      - name: Tests
        run: poetry run pytest --cov=src --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
